export const salesAreas: string[] = [
    "BUSINESS BAY",
    "Al Wasl",
    "JUMEIRAH LAKES TOWERS",
    "JUMEIRAH VILLAGE CIRCLE",
    "DUBAI CREEK HARBOUR",
    "Madinat Dubai Almelaheyah",
    "DUBAI WATER CANAL",
    "DUBAI MARINA",
    "Business Bay",
    "TOWN SQUARE",
    "Al Yufrah 1",
    "Zaabeel First",
    "SOBHA HEARTLAND",
    "MEYDAN ONE",
    "DAMAC HILLS",
    "JUMEIRAH VILLAGE TRIANGLE",
    "BURJ KHALIFA",
    "DUBAI LAND RESIDENCE COMPLEX",
    "Wadi Al Safa 5",
    "Wadi Al Safa 3",
    "THE FIELD",
    "Me'Aisem First",
    "Nad Al Shiba First",
    "PALM JUMEIRAH",
    "DUBAI HILLS",
    "SILICON OASIS",
    "JUMEIRAH LIVING",
    "TECOM SITE A",
    "DOWN TOWN JABAL ALI",
    "Um Suqaim Third",
    "AL FURJAN",
    "Marsa Dubai",
    "MOTOR CITY",
    "VILLANOVA",
    "ARJAN",
    "Al Hebiah Fourth",
    "DUBAI SOUTH",
    "Madinat Hind 4",
    "DUBAI HARBOUR",
    "Warsan First",
    "Island 2",
    "CITY WALK",
    "Al Yelayiss 2",
    "CHERRYWOODS",
    "TILAL AL GHAF",
    "DUBAI STUDIO CITY",
    "DUBAI PRODUCTION CITY",
    "THE LAKES",
    "MBR DISTRICT 7",
    "MINA RASHID",
    "Hadaeq Sheikh Mohammed Bin Rashid",
    "THE VALLEY",
    "ARABIAN RANCHES III",
    "EMAAR SOUTH",
    "DUBAI SCIENCE PARK",
    "Jumeirah First",
    "LA MER",
    "MBR DISTRICT 1",
    "Madinat Al Mataar",
    "LIWAN",
    "Al Hebiah Sixth",
    "MAJAN",
    "DUBAI SPORTS CITY",
    "JUMEIRAH BEACH RESIDENCE",
    "Al Barshaa South Third",
    "Wadi Al Safa 7",
    "JUMEIRA BAY",
    "Zaabeel Second",
    "DUBAI HEALTHCARE CITY - PHASE 2",
    "THE WORLD",
    "INTERNATIONAL CITY PH 2 & 3",
    "RUKAN",
    "JADDAF WATERFRONT",
    "MEYDAN AVENUE",
    "DUBAI GOLF CITY",
    "Jumeirah Second",
    "LIVING LEGENDS",
    "DUBAI MARITIME CITY",
    "JUMEIRAH GOLF",
    "Wadi Al Safa 2",
    "DUBAI DESIGN DISTRICT",
    "SUFOUH GARDENS",
    "MARSA AL ARAB",
    "PALMAROSA",
    "Al Kifaf",
    "Al Merkadh",
    "Jabal Ali First",
    "Palm Deira",
    "Wadi Al Safa 4",
    "INTERNATIONAL CITY PH 1",
    "DISCOVERY GARDENS",
    "Naif",
    "Palm Jumeirah",
    "ARABIAN RANCHES I",
    "DUBAI WATER FRONT",
    "MIRA",
    "REMRAAM",
    "BARSHA HEIGHTS",
    "BLUEWATERS",
    "THE GREENS",
    "JABEL ALI HILLS",
    "Mirdif",
    "JUMEIRAH PARK",
    "EMIRATE LIVING",
    "Al Karama",
    "Al Rashidiya",
    "ARABIAN RANCHES II",
    "SERENA",
    "THE VILLA",
    "AL BARARI",
    "Al Mizhar First",
    "Al Mamzer",
    "LIWAN 2",
    "JUMEIRAH HEIGHTS",
    "GRAND VIEWS",
    "PEARL JUMEIRA",
    "NAD AL SHEBA GARDENS",
    "JUMEIRAH ISLANDS",
    "Nad Al Shiba Third",
    "MUDON",
    "Al Thanyah Fifth",
    "Al Barshaa South First",
    "AL KHAIL HEIGHTS",
    "Al Barsha First",
    "Abu Hail",
    "Al Waheda",
    "Hor Al Anz",
    "Al Aweer First",
    "MILLENNIUM",
    "Al Layan1",
    "Mugatrah",
    "Al Goze Second",
    "Al Mizhar Second",
    "Al Goze First",
    "AKOYA OXYGEN",
    "SUSTAINABLE CITY",
    "Al Barsha Second",
    "Al Khawaneej Second",
    "SAMA AL JADAF",
    "Al Kheeran",
    "DUBAI INDUSTRIAL CITY",
    "Al Saffa First",
    "Al Satwa",
    "Wadi Alshabak",
    "FALCON CITY OF WONDERS",
    "Um Suqaim Second",
    "AL WAHA",
    "Al Ras",
    "Muhaisanah Third",
    "Jabal Ali Industrial First",
    "Al Saffa Second",
    "Um Al Sheif",
    "Al Bada",
    "DUBAI HEALTHCARE CITY - PHASE 1",
    "Al Warqa First",
    "Al Murqabat",
    "Al Warqa Third",
    "Muhaisanah First",
    "Al Jafliya",
    "Al Lusaily",
    "Trade Center First",
    "CITY OF ARABIA",
    "ARABIAN RANCHES POLO CLUB",
    "Port Saeed",
    "Al Baraha",
    "Nad Al Hamar",
    "Eyal Nasser",
    "MEDYAN RACE COURSE VILLAS",
    "DMCC-EZ2",
    "Al Twar Fourth",
    "Nad Al Shiba Fourth",
    "Al Khawaneej First",
    "Al Barsha Third",
    "Al Manara",
    "Muhaisanah Second",
    "Nad Al Shiba Second",
    "Al Aweer Second",
    "Mankhool",
    "Al Hamriya",
    "Al Suq Al Kabeer",
    "Um Suqaim First",
    "POLO TOWNHOUSES IGO",
    "Wadi Al Amardi",
    "Al Mararr",
    "Jumeirah Third",
    "Al Muteena",
    "Hor Al Anz East",
    "Al Barshaa South Second",
    "Al Thanyah Third",
    "Al Goze Fourth",
    "Al Twar Third",
    "Ras Al Khor Industrial Second",
    "Al Hebiah Second",
    "Al Buteen",
    "Muhaisanah Fourth",
    "Al Warqa Second",
    "Al Nahda First",
    "Oud Metha",
    "Al Warsan Second",
    "Al Nahda Second",
    "Al Garhoud",
    "Al Goze Industrial Third",
    "Al Khabeesi",
    "Al Qusais Industrial Fifth",
    "Al Raffa",
    "Al Goze Third",
    "Al Qusais First",
    "Rega Al Buteen",
    "Trade Center Second",
    "Al Twar First",
    "Ras Al Khor Industrial First",
    "BUSINESS PARK",
    "Al Warqa Fourth",
    "Oud Al Muteena First",
    "Al Goze Industrial Fourth",
    "HORIZON",
    "Lehbab First",
    "Nad Shamma",
    "PALM DEIRA",
    "Al Safouh Second",
    "Al Safouh First",
    "Al Goze Industrial Second",
    "Al Yufrah 4",
    "Al Mizhar Third",
    "Al Dhagaya",
    "Al Qusais Industrial Fourth",
    "Al Jadaf",
    "GLOBAL VILLAGE",
    "Grayteesah",
    "Al Twar Second",
    "DUBAI OUTSOURCE CITY",
    "DUBAI INVESTMENT PARK FIRST",
    "Madinat Hind 1",
    "Dubai Investment Park Second",
    "Nadd Hessa",
    "Saih Shuaib 3",
    "Saih Shuaib 4",
    "Saih Shuaib 2",
    "DUBAI INVESTMENT PARK SECOND",
    "Al Hebiah Fifth",
    "Al Hebiah Third",
    "Me'Aisem Second",
    "Palm Jabal Ali",
    "Dubai Investment Park First"
];

export const rentalAreas: string[] = [
    "Al Barsha First",
    "Al Karama",
    "Ras Al Khor Industrial Third",
    "Al Rega",
    "Oud Metha",
    "Jabal Ali Industrial First",
    "Al Qusais First",
    "Muhaisanah Second",
    "Al Goze Industrial Second",
    "Al Nahda Second",
    "Al Murqabat",
    "Al Qusais Industrial Third",
    "Al Warsan Third",
    "Ras Al Khor Industrial Second",
    "Jabal Ali First",
    "Al Safouh First",
    "Muhaisanah Fourth",
    "Mirdif",
    "Al Suq Al Kabeer",
    "Al Nahda First",
    "Al Qusais Industrial Second",
    "Al Qusais Industrial Fourth",
    "Al Ras",
    "Al Wasl",
    "Al Muteena",
    "Hor Al Anz East",
    "Hor Al Anz",
    "Al Goze Fourth",
    "Trade Center First",
    "Al Goze Industrial Fourth",
    "Abu Hail",
    "Al Mararr",
    "Al Bada",
    "Um Hurair First",
    "Eyal Nasser",
    "Naif",
    "Al Hudaiba",
    "Al Goze Industrial First",
    "Um Ramool",
    "Al Qusais Second",
    "Al Warsan First",
    "Al Dhagaya",
    "Um Hurair Second",
    "Madinat Dubai Almelaheyah",
    "Al Khawaneej First",
    "Port Saeed",
    "Al Saffa First",
    "Al Goze First",
    "Saih Shuaib 2",
    "Al Rashidiya",
    "Al Satwa",
    "Al Barsha Second",
    "Ras Al Khor Industrial First",
    "Mankhool",
    "Al Sabkha",
    "Rega Al Buteen",
    "Al Goze Industrial Third",
    "Trade Center Second",
    "Al Raffa",
    "Madinat Hind 1",
    "Al Saffa Second",
    "Al Baraha",
    "Al Khabeesi",
    "Nad Al Hamar",
    "Um Al Sheif",
    "Al Garhoud",
    "Al Safouh Second",
    "Um Suqaim Third",
    "Al Thanyah First",
    "Dubai Investment Park First",
    "Al Buteen",
    "Um Suqaim First",
    "Al Qusais Industrial First",
    "Burj Khalifa",
    "Jumeirah First",
    "Al Hamriya",
    "Marsa Dubai",
    "Nadd Hessa",
    "Business Bay",
    "Al Jafliya",
    "Jumeirah Third",
    "Al Mamzer",
    "Al Waheda",
    "Jumeirah Second",
    "Dubai International Airport",
    "Al Goze Third",
    "Al Mizhar First",
    "Um Suqaim Second",
    "Al Ttay",
    "Al Qusais Industrial Fifth",
    "Al Thanyah Fifth",
    "Al Kheeran",
    "Al Warqa First",
    "Wadi Al Safa 7",
    "Al Manara",
    "Dubai Investment Park Second",
    "Wadi Al Safa 3",
    "Al Thanayah Fourth",
    "Warsan Fourth",
    "Al Hebiah Fourth",
    "Al Khawaneej Second",
    "Al Twar First",
    "Wadi Al Safa 5",
    "Al Aweer Second",
    "Muhaisanah First",
    "Al Barsha South Fifth",
    "Al Aweer First",
    "Al Hebiah Fifth",
    "Al Hebiah First",
    "Al Warsan Second",
    "Zaabeel First",
    "Me'Aisem First",
    "Al Thanyah Third",
    "Al Barsha South Fourth",
    "Al Barshaa South First",
    "Hessyan First",
    "Palm Jumeirah",
    "Al Barshaa South Second",
    "Zaabeel Second",
    "Saih Shuaib 3",
    "Al Barshaa South Third",
    "Wadi Al Amardi",
    "Al Jadaf",
    "Oud Al Muteena First",
    "Hatta",
    "Mena Jabal Ali",
    "Saih Shuaib 1",
    "Al Twar Third",
    "Al Hebiah Sixth",
    "Al Barsha Third",
    "Jabal Ali",
    "Wadi Al Safa 2",
    "Lehbab Second",
    "Cornich Deira",
    "Al Hebiah Second",
    "Al-Cornich",
    "Al Warqa Third",
    "Al Yelayiss 1",
    "Al Warqa Fourth",
    "Wadi Al Safa 6",
    "Madinat Al Mataar",
    "Nad Al Shiba Third",
    "Al Rowaiyah First",
    "Saih Shuaib 4",
    "Nad Al Shiba First",
    "Al Marmoom",
    "Al Hebiah Third",
    "Al Yelayiss 2",
    "Al Goze Second",
    "Jabal Ali Industrial Second",
    "Al Twar Second",
    "Nad Al Shiba Second",
    "Margham",
    "Lehbab First",
    "Shandagha",
    "Al Lusaily",
    "Al Yufrah 1",
    "Al Twar Fourth",
    "Al Mizhar Second",
    "Wadi Al Safa 4",
    "Al Maha",
    "Hadaeq Sheikh Mohammed Bin Rashid",
    "Oud Almuteena Second",
    "Al Khairan First",
    "Nad Shamma",
    "Madinat Hind 4",
    "Al Warqa Second",
    "Muhaisanah Third",
    "Al Hamriya Port",
    "Grayteesah",
    "Al Merkadh",
    "Nad Al Shiba Fourth",
    "Al Mizhar Third",
    "Bukadra",
    "Al Rowaiyah Third",
    "Island 2",
    "Al Kifaf",
    "Hessyan Second",
    "Madinat Hind 3",
    "Palm Deira",
    "Al Ruwayyah",
    "Muragab",
    "Al Eyas",
    "Al Yufrah 2",
    "Al Yufrah 3",
    "Nad Al Shiba",
    "Wadi Alshabak",
    "Mushrif",
    "Al Qoaz",
    "Al Rowaiyah Second",
    "Madinat Hind 2",
    "Nazwah",
    "Al-Raulah",
    "Bur Dubai",
    "Lehbab",
    "Al Qusais"
];
